CREATE DATABASE :DATABASE;
CREATE USER ':USER'@'%' IDENTIFIED BY ':PASSWORD';
GRANT ALL PRIVILEGES ON * . * TO ':USER'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY ':ROOT_PASSWORD';
FLUSH PRIVILEGES;